
################################################################################
# Monitoring Cluster
################################################################################
start_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml up

destroy_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml destroy

halt_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml halt

reload_monitoring: 
	vagrant --design=designs/Vagrant_monitoring.yaml reload

status_monitoring:
	vagrant --design=designs/Vagrant_monitoring.yaml status

################################################################################
# EFD Cluster
################################################################################

start_efd:
	vagrant --design=designs/Vagrant_efd.yaml up

destroy_efd:
	vagrant --design=designs/Vagrant_efd.yaml destroy

halt_efd:
	vagrant --design=designs/Vagrant_efd.yaml halt

reload_efd: 
	vagrant --design=designs/Vagrant_efd.yaml reload

status_efd: 
	vagrant --design=designs/Vagrant_efd.yaml status