CPUS="1"
MEMORY="1024"


$script = <<SCRIPT
#!/bin/bash

PUPPET_ENV=$1
sed "s/NM_CONTROLLED=yes/NM_CONTROLLED=no/" -i /etc/sysconfig/network-scripts/ifcfg-eth1
systemctl restart NetworkManager
# support RPM for puppetserver installation
rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
chmod 755 /opt/puppetlabs/puppet/cache/
# puppet installation plus some other utilities
yum install -y puppet-agent vim git xauth
echo -e "\n[main]\nenvironment = $PUPPET_ENV" >> /etc/puppetlabs/puppet/puppet.conf
echo -e "\n[agent]\nserver = puppet-master.dev.lsst.org" >> /etc/puppetlabs/puppet/puppet.conf
echo -e "10.0.0.250\tpuppet-master\tpuppet-master.dev.lsst.org" > /etc/hosts
/opt/puppetlabs/puppet/bin/puppet agent -t
SCRIPT

###################################################
# Monitoring Cluster definition                   #
###################################################

Vagrant.configure("2") do |config|

	config.vm.box = "centos/7"
	config.ssh.forward_x11 = true

	# InfluxDB
	config.vm.define "influx" do |influx|
		influx.vm.hostname = "gs-influxdb-node-01.dev.lsst.org"
		influx.vm.provision "shell" do |s|
			s.inline = $script
			s.args = "develop"
		end
		influx.vm.network "private_network", ip: "10.0.0.251"
		config.vm.provider "virtualbox" do |v|
			v.name = "InfluxDB"
			v.memory = MEMORY
			v.cpus = CPUS
		end
	end

	# Grafana
	config.vm.define "grafana" do |grafana|
		grafana.vm.hostname = "gs-grafana-node-01.dev.lsst.org"
		grafana.vm.provision "shell" do |s|
			s.inline = $script
			s.args = "develop"
		end
		grafana.vm.network "private_network", ip: "10.0.0.252"
		config.vm.provider "virtualbox" do |v|
			v.name = "Grafana"
			v.memory = MEMORY
			v.cpus = CPUS
		end
	end

	# Graylog
	config.vm.define "graylog" do |graylog|
		graylog.vm.hostname = "gs-graylog-node-01.dev.lsst.org"
		graylog.vm.provision "shell" do |s|
			s.inline = $script
			s.args = "develop"
		end
		graylog.vm.network "private_network", ip: "10.0.0.253"
		config.vm.provider "virtualbox" do |v|
			v.name = "Graylog"
			v.memory = 2048
			v.cpus = 2
		end
	end

###################################################
# New servers not part of the monitoring Cluster  #
###################################################

	# EFD
	config.vm.define "EFD" do |efd|
		efd.vm.hostname = "ts-efd-node-01.dev.lsst.org"
		efd.vm.provision "shell" do |s|
			s.inline = $script
			s.args = "develop"
		end
		efd.vm.network "private_network", ip: "10.0.0.10"
		config.vm.provider "virtualbox" do |v|
			v.name = "EFD"
			v.memory = MEMORY
			v.cpus = CPUS
		end
	 end

	# ATS Shutter HCU
	config.vm.define "ats-shutter-hcu" do |custom_vm|
		custom_vm.vm.hostname = "ats-shutter-hcu.dev.lsst.org"
		custom_vm.vm.provision "shell" do |s|
			s.inline = $script
			s.args = "TSEIA_57_avillalobos"
		end
		custom_vm.vm.network "private_network", ip: "10.0.0.20"
		config.vm.provider "virtualbox" do |v|
			v.name = "ats-shutter-hcu"
			v.memory = MEMORY
			v.cpus = CPUS
		end
	end

	# DM Header Service
	config.vm.define "dm-hs" do |custom_vm|
		custom_vm.vm.hostname = "dm-hs-node-01.dev.lsst.org"
		custom_vm.vm.provision "shell" do |s|
			s.inline = $script
			s.args = "develop"
		end
		custom_vm.vm.network "private_network", ip: "10.0.0.30"
		config.vm.provider "virtualbox" do |v|
			v.name = "dm-hs"
			v.memory = MEMORY
			v.cpus = CPUS
		end
	end

end
