CPUS="1"
MEMORY="2048"
VAGRANT_HOSTNAME="gs-puppet-master.vm.dev.lsst.org"


$script = <<SCRIPT
#!/bin/bash

rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
yum install -y puppetserver git
sed -i 's#\-Xms2g#\-Xms512m#g;s#\-Xmx2g#\-Xmx512m#g' /etc/sysconfig/puppetserver
echo -e "certname = puppet-master.dev.lsst.org" >> /etc/puppetlabs/puppet/puppet.conf
echo -e "\n[main]\nenvironment = TSEIA_57_avillalobos" >> /etc/puppetlabs/puppet/puppet.conf
echo -e "\n[agent]\nserver = puppet-master.dev.lsst.org" >> /etc/puppetlabs/puppet/puppet.conf
echo -e "10.0.0.250\tpuppet-master\tpuppet-master.dev.lsst.org" > /etc/hosts
systemctl enable puppetserver
systemctl start puppetserver
sed -i 's#^PATH=.*#PATH=$PATH:/opt/puppetlabs/puppet/bin:$HOME/bin#g' /root/.bash_profile
#/opt/puppetlabs/puppet/bin/gem install cri -v 2.12.0
/opt/puppetlabs/puppet/bin/gem install r10k
mkdir -p /etc/puppetlabs/r10k/
if [ -d /root/hiera ]
then 
	echo "Hiera repo exists, deleted to be overwritten"
	rm -rvf /root/hiera 
fi
mv /tmp/hiera /root/
git init /root/hiera/
cd /root/hiera
git checkout -b develop
git add .
git commit -m "Initial Commit"

echo -e "---
:cachedir: '/var/cache/r10k'

:sources:
  :lsst.org:
    remote: 'https://github.com/lsst/itconf_l1ts.git'
    basedir: '/etc/puppetlabs/code/environments'
  :lsst_hiera:
    remote: '/root/hiera/.git'
    basedir: '/etc/puppetlabs/code/hieradata'
" > /etc/puppetlabs/r10k/r10k.yaml

/opt/puppetlabs/puppet/bin/r10k deploy environment -p

for f in $(ls -1 /etc/puppetlabs/code/environments/)
do 
	if [ ! -d "/etc/puppetlabs/code/hieradata/$f" ]
	then
		echo "dir $f don't exists, creating it from develop"
		cp -rvf /etc/puppetlabs/code/hieradata/develop /etc/puppetlabs/code/hieradata/$f
	fi
done

# Registering against the puppet server and sending certificate
/opt/puppetlabs/puppet/bin/puppet agent -t
# Given that this newly created cert isnt' known by puppet master, we need to sign it.
/opt/puppetlabs/puppet/bin/puppet cert sign -a
# Asking for the catalog again
/opt/puppetlabs/puppet/bin/puppet agent -t

SCRIPT

Vagrant.configure("2") do |config|
	config.vm.define "puppet-master" do |puppet|
		puppet.vm.box = "centos/7"
		puppet.vm.hostname = VAGRANT_HOSTNAME
		puppet.vm.provision "file", source: "./hiera", destination: "/tmp/hiera"
		puppet.vm.provision "shell" do |s|
			s.inline = $script
			s.args = VAGRANT_HOSTNAME
		end

		puppet.vm.network "private_network", ip: "10.0.0.250"
		puppet.ssh.forward_x11 = true
		puppet.vm.provider "virtualbox" do |v|
			v.name = VAGRANT_HOSTNAME
			v.memory = MEMORY
			v.cpus = CPUS
		end
	end
end
