require 'yaml'
require 'pp'

conf = YAML.load_file( "Puppetconf.yaml" )
Puppetconf = conf["puppet-master"]

Vagrant.configure("2") do |config|
	config.vm.define "puppet-master" do |puppet|
		puppet.vm.box = "centos/7"
		puppet.vm.hostname = Puppetconf["hostname"]
		puppet.vm.synced_folder '.', '/vagrant'
		puppet.vm.synced_folder Puppetconf["gitcode_path"], "/opt/puppet-code"
		puppet.vm.synced_folder "hiera", "/etc/puppetlabs/code/hieradata/production"
		puppet.vm.provision :shell, :path => 'provision-script.sh', :args => [Puppetconf["puppet_environment"], Puppetconf["ip"]]
		puppet.vm.network "private_network", ip: Puppetconf["ip"]
		puppet.ssh.forward_x11 = true
		puppet.vm.provider "virtualbox" do |v|
			v.name = Puppetconf["hostname"]
			v.memory = Puppetconf["memory"]
			v.cpus = Puppetconf["cpu"]
		end
	end
end
